<?php
require_once __DIR__.'/app/bootstrap.php';
$active='blog';
$metaTitle='Blog | '.setting('site_name','Vera Yapı');
$metaDescription='İnşaat, konut yatırımı, anahtar teslim ve proje yönetimi hakkında rehber içerikler.';
$canonical=app_url('blog');
$breadcrumbs=[['name'=>'Ana Sayfa','url'=>app_url()],['name'=>'Blog','url'=>$canonical]];
$pageSchema=['@type'=>'Blog','@id'=>$canonical.'#blog','url'=>$canonical,'name'=>$metaTitle,'description'=>$metaDescription,'publisher'=>['@id'=>rtrim(app_url(),'/').'#business']];
$items=rows('posts','is_active=1',[],'COALESCE(published_at,created_at) DESC,id DESC');
include __DIR__.'/partials/header.php';
?>
<main id="icerik"><section class="page-hero-modern"><div class="container"><div class="page-breadcrumb"><a href="<?= e(app_url()) ?>">Ana Sayfa</a><span>/</span><span>Blog</span></div><div class="home-kicker">Bilgi Merkezi</div><h1>İnşaat ve yatırım kararları için anlaşılır rehberler.</h1><p>Projenizi planlarken teknik ve ticari açıdan doğru soruları sormanıza yardımcı olacak içerikler.</p></div></section><section class="page-section"><div class="container"><?php $fallbacks=['https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&q=82&w=1000','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=82&w=1000','https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=82&w=1000']; ?><div class="page-grid-3"><?php foreach($items as $i=>$p): ?><article class="list-card"><a href="<?= e(app_url('blog/'.$p['slug'])) ?>"><img src="<?= e(media_url($p['cover_image'] ?: $fallbacks[$i%3])) ?>" alt="<?= e($p['image_alt'] ?: $p['title']) ?>"<?php if(!empty($p['image_title'])): ?> title="<?= e($p['image_title']) ?>"<?php endif; ?> loading="lazy"></a><small><?= e($p['published_at']?date('d.m.Y',strtotime($p['published_at'])):'Rehber') ?></small><h2><a class="title-link" href="<?= e(app_url('blog/'.$p['slug'])) ?>"><?= e($p['title']) ?></a></h2><p><?= e($p['excerpt']) ?></p></article><?php endforeach; ?></div></div></section><section class="page-section" style="padding-top:0"><div class="container"><div class="page-cta"><div><div class="home-kicker">Projenizi Konuşalım</div><h2>Doğru kapsamı birlikte netleştirelim.</h2><p>Proje türünü, konumu ve hedefinizi paylaşın; ilk değerlendirmede hangi hizmete ihtiyacınız olduğunu birlikte belirleyelim.</p></div><div class="page-cta-actions"><a class="home-btn home-btn-primary" href="<?= e(app_url('#teklif')) ?>">Ücretsiz Keşif Talebi</a><a class="home-btn home-btn-secondary" href="https://wa.me/<?= e(preg_replace('/\D+/','',setting('whatsapp',setting('phone')))) ?>?text=<?= rawurlencode('Merhaba Vera Yapı, projem hakkında detaylı bilgi almak istiyorum.') ?>" target="_blank" rel="noopener">WhatsApp'tan Yaz</a></div></div></div></section></main>
<?php include __DIR__.'/partials/footer.php'; ?>
