<?php
require_once __DIR__.'/app/bootstrap.php';
$slug=trim((string)($_GET['slug']??''));$item=one_by_slug('projects',$slug);
if(!$item){http_response_code(404);$robots='noindex';$metaTitle='Proje Bulunamadı';include __DIR__.'/partials/header.php';echo '<main id="icerik"><section class="page-hero-modern"><div class="container"><h1>Proje bulunamadı.</h1></div></section></main>';include __DIR__.'/partials/footer.php';exit;}
$active='projects';$metaTitle=$item['meta_title'] ?: $item['title'].' | '.setting('site_name','Vera Yapı');$metaDescription=$item['meta_description'] ?: $item['summary'];$ogImage=$item['cover_image'];
$gallery=json_decode((string)$item['gallery_json'],true);if(!is_array($gallery))$gallery=[];
include __DIR__.'/partials/header.php';
?>
<main id="icerik"><section class="detail-hero"><div class="container detail-hero-grid"><div><div class="home-kicker"><?= e($item['status']) ?></div><h1><?= e($item['title']) ?></h1><p><?= e($item['summary']) ?></p><div class="detail-meta"><span><b>Konum</b><?= e($item['location']) ?></span><span><b>Tür</b><?= e($item['category']) ?></span><span><b>Alan</b><?= e($item['area']) ?></span><span><b>Yıl</b><?= e($item['project_year']) ?></span></div></div><img src="<?= e(media_url($item['cover_image'])) ?>" alt="<?= e($item['title']) ?>"></div></section><section class="page-section"><div class="container content-layout"><article class="content-prose"><p class="lead"><?= e($item['summary']) ?></p><?php foreach(preg_split('/\R{2,}/',(string)$item['body']) as $p): ?><p><?= nl2br(e($p)) ?></p><?php endforeach; ?><?php if($gallery): ?><div class="gallery-grid"><?php foreach($gallery as $img): ?><img src="<?= e(media_url((string)$img)) ?>" alt="<?= e($item['title']) ?> proje görseli" loading="lazy"><?php endforeach; ?></div><?php endif; ?></article><aside class="detail-aside"><h3>Benzer bir proje mi planlıyorsunuz?</h3><p>Konum ve yaklaşık proje bilgilerini paylaşın; ilk değerlendirmeyi birlikte yapalım.</p><a class="home-btn home-btn-primary" href="<?= e(app_url('#teklif')) ?>">Teklif Alın</a><a class="home-btn home-btn-secondary" href="<?= e(app_url('projeler')) ?>">Tüm Projeler</a></aside></div></section></main>
<?php include __DIR__.'/partials/footer.php'; ?>
